USE QuanLyThuVien;
GO

-- Tắt FK tạm thời
EXEC sp_MSforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL';
GO

-- =====================================================
-- ĐỔI MÃ CONNGUOI: CN001-CN010 → DG001-DG010
--                   CN011-CN020 → NV001-NV010
-- =====================================================

-- CONNGUOI
UPDATE CONNGUOI SET MaNguoi = 'DG001' WHERE MaNguoi = 'CN001';
UPDATE CONNGUOI SET MaNguoi = 'DG002' WHERE MaNguoi = 'CN002';
UPDATE CONNGUOI SET MaNguoi = 'DG003' WHERE MaNguoi = 'CN003';
UPDATE CONNGUOI SET MaNguoi = 'DG004' WHERE MaNguoi = 'CN004';
UPDATE CONNGUOI SET MaNguoi = 'DG005' WHERE MaNguoi = 'CN005';
UPDATE CONNGUOI SET MaNguoi = 'DG006' WHERE MaNguoi = 'CN006';
UPDATE CONNGUOI SET MaNguoi = 'DG007' WHERE MaNguoi = 'CN007';
UPDATE CONNGUOI SET MaNguoi = 'DG008' WHERE MaNguoi = 'CN008';
UPDATE CONNGUOI SET MaNguoi = 'DG009' WHERE MaNguoi = 'CN009';
UPDATE CONNGUOI SET MaNguoi = 'DG010' WHERE MaNguoi = 'CN010';
UPDATE CONNGUOI SET MaNguoi = 'NV001' WHERE MaNguoi = 'CN011';
UPDATE CONNGUOI SET MaNguoi = 'NV002' WHERE MaNguoi = 'CN012';
UPDATE CONNGUOI SET MaNguoi = 'NV003' WHERE MaNguoi = 'CN013';
UPDATE CONNGUOI SET MaNguoi = 'NV004' WHERE MaNguoi = 'CN014';
UPDATE CONNGUOI SET MaNguoi = 'NV005' WHERE MaNguoi = 'CN015';
UPDATE CONNGUOI SET MaNguoi = 'NV006' WHERE MaNguoi = 'CN016';
UPDATE CONNGUOI SET MaNguoi = 'NV007' WHERE MaNguoi = 'CN017';
UPDATE CONNGUOI SET MaNguoi = 'NV008' WHERE MaNguoi = 'CN018';
UPDATE CONNGUOI SET MaNguoi = 'NV009' WHERE MaNguoi = 'CN019';
UPDATE CONNGUOI SET MaNguoi = 'NV010' WHERE MaNguoi = 'CN020';

-- DOCGIA
UPDATE DOCGIA SET MaDocGia = 'DG001' WHERE MaDocGia = 'CN001';
UPDATE DOCGIA SET MaDocGia = 'DG002' WHERE MaDocGia = 'CN002';
UPDATE DOCGIA SET MaDocGia = 'DG003' WHERE MaDocGia = 'CN003';
UPDATE DOCGIA SET MaDocGia = 'DG004' WHERE MaDocGia = 'CN004';
UPDATE DOCGIA SET MaDocGia = 'DG005' WHERE MaDocGia = 'CN005';
UPDATE DOCGIA SET MaDocGia = 'DG006' WHERE MaDocGia = 'CN006';
UPDATE DOCGIA SET MaDocGia = 'DG007' WHERE MaDocGia = 'CN007';
UPDATE DOCGIA SET MaDocGia = 'DG008' WHERE MaDocGia = 'CN008';
UPDATE DOCGIA SET MaDocGia = 'DG009' WHERE MaDocGia = 'CN009';
UPDATE DOCGIA SET MaDocGia = 'DG010' WHERE MaDocGia = 'CN010';

-- NGUOIQUANLY
UPDATE NGUOIQUANLY SET MaNQL = 'NV001' WHERE MaNQL = 'CN011';
UPDATE NGUOIQUANLY SET MaNQL = 'NV002' WHERE MaNQL = 'CN012';
UPDATE NGUOIQUANLY SET MaNQL = 'NV003' WHERE MaNQL = 'CN013';
UPDATE NGUOIQUANLY SET MaNQL = 'NV004' WHERE MaNQL = 'CN014';
UPDATE NGUOIQUANLY SET MaNQL = 'NV005' WHERE MaNQL = 'CN015';
UPDATE NGUOIQUANLY SET MaNQL = 'NV006' WHERE MaNQL = 'CN016';
UPDATE NGUOIQUANLY SET MaNQL = 'NV007' WHERE MaNQL = 'CN017';
UPDATE NGUOIQUANLY SET MaNQL = 'NV008' WHERE MaNQL = 'CN018';
UPDATE NGUOIQUANLY SET MaNQL = 'NV009' WHERE MaNQL = 'CN019';
UPDATE NGUOIQUANLY SET MaNQL = 'NV010' WHERE MaNQL = 'CN020';

-- THETHUVIEN (MaDocGia + MaNQL)
UPDATE THETHUVIEN SET MaDocGia = 'DG001' WHERE MaDocGia = 'CN001';
UPDATE THETHUVIEN SET MaDocGia = 'DG002' WHERE MaDocGia = 'CN002';
UPDATE THETHUVIEN SET MaDocGia = 'DG003' WHERE MaDocGia = 'CN003';
UPDATE THETHUVIEN SET MaDocGia = 'DG004' WHERE MaDocGia = 'CN004';
UPDATE THETHUVIEN SET MaDocGia = 'DG005' WHERE MaDocGia = 'CN005';
UPDATE THETHUVIEN SET MaDocGia = 'DG006' WHERE MaDocGia = 'CN006';
UPDATE THETHUVIEN SET MaDocGia = 'DG007' WHERE MaDocGia = 'CN007';
UPDATE THETHUVIEN SET MaDocGia = 'DG008' WHERE MaDocGia = 'CN008';
UPDATE THETHUVIEN SET MaDocGia = 'DG009' WHERE MaDocGia = 'CN009';
UPDATE THETHUVIEN SET MaDocGia = 'DG010' WHERE MaDocGia = 'CN010';
UPDATE THETHUVIEN SET MaNQL = 'NV001' WHERE MaNQL = 'CN011';
UPDATE THETHUVIEN SET MaNQL = 'NV002' WHERE MaNQL = 'CN012';
UPDATE THETHUVIEN SET MaNQL = 'NV004' WHERE MaNQL = 'CN014';
UPDATE THETHUVIEN SET MaNQL = 'NV006' WHERE MaNQL = 'CN016';
UPDATE THETHUVIEN SET MaNQL = 'NV008' WHERE MaNQL = 'CN018';

-- PHIEUMUON (MaNQL)
UPDATE PHIEUMUON SET MaNQL = 'NV001' WHERE MaNQL = 'CN011';
UPDATE PHIEUMUON SET MaNQL = 'NV002' WHERE MaNQL = 'CN012';
UPDATE PHIEUMUON SET MaNQL = 'NV004' WHERE MaNQL = 'CN014';
UPDATE PHIEUMUON SET MaNQL = 'NV006' WHERE MaNQL = 'CN016';
UPDATE PHIEUMUON SET MaNQL = 'NV008' WHERE MaNQL = 'CN018';

-- PHIEUNHAP (MaNQL)
UPDATE PHIEUNHAP SET MaNQL = 'NV001' WHERE MaNQL = 'CN011';
UPDATE PHIEUNHAP SET MaNQL = 'NV002' WHERE MaNQL = 'CN012';
UPDATE PHIEUNHAP SET MaNQL = 'NV004' WHERE MaNQL = 'CN014';
UPDATE PHIEUNHAP SET MaNQL = 'NV006' WHERE MaNQL = 'CN016';
UPDATE PHIEUNHAP SET MaNQL = 'NV008' WHERE MaNQL = 'CN018';

-- PHIEUPHAT (MaNQL) nếu có
UPDATE PHIEUPHAT SET MaNQL = 'NV001' WHERE MaNQL = 'CN011';
UPDATE PHIEUPHAT SET MaNQL = 'NV002' WHERE MaNQL = 'CN012';
UPDATE PHIEUPHAT SET MaNQL = 'NV004' WHERE MaNQL = 'CN014';
UPDATE PHIEUPHAT SET MaNQL = 'NV006' WHERE MaNQL = 'CN016';
UPDATE PHIEUPHAT SET MaNQL = 'NV008' WHERE MaNQL = 'CN018';

-- Bật lại FK
EXEC sp_MSforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL';
GO

PRINT N'✅ Đổi mã thành công! Dùng admin01/admin123 để đăng nhập Admin.';